version: '3.8'

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=db_pw
      - DB_NAME=db_name
    ports:
      - "5000:5000"  
  db:
    image: mysql:8.0
    restart: always
    #command: ["mysqld","--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: db_pw
      MYSQL_DATABASE: db_name
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
    ports:
      - "3306:3306"

volumes:
 db_data:

networks:
 app_network:
